# -*- coding: utf-8 -*-
# Lista completa de canales de Balandro
# Total: 203 canales

ALL_CHANNELS = [
    {"id": "absoluporn", "name": "AbsoluPorn", "types": ["movie"]},
    {"id": "allpeliculasse", "name": "AllPeliculasSe", "types": ["movie", "series"]},
    {"id": "animeclub", "name": "AnimeClub", "types": ["series"]},
    {"id": "animeflv", "name": "AnimeFlv", "types": ["series"]},
    {"id": "animejl", "name": "AnimeJl", "types": ["series"]},
    {"id": "animemix", "name": "AnimeMix", "types": ["series"]},
    {"id": "animeonline", "name": "AnimeOnline", "types": ["series"]},
    {"id": "animeyt", "name": "AnimeYt", "types": ["series"]},
    {"id": "area51", "name": "Area51", "types": ["movie"]},
    {"id": "areadocumental", "name": "AreaDocumental", "types": ["movie", "series"]},
    {"id": "areshd", "name": "AresHd", "types": ["movie", "series"]},
    {"id": "asialive", "name": "AsiaLive", "types": ["movie", "series"]},
    {"id": "beeg", "name": "Beeg", "types": ["movie"]},
    {"id": "bloghorror", "name": "BlogHorror", "types": ["movie"]},
    {"id": "cam4", "name": "Cam4", "types": ["movie"]},
    {"id": "ciberdocumentales", "name": "CiberDocumentales", "types": ["movie", "series"]},
    {"id": "cine24h", "name": "Cine24H", "types": ["movie", "series"]},
    {"id": "cinecalidad", "name": "CineCalidad", "types": ["movie", "series"]},
    {"id": "cinecalidadla", "name": "CineCalidadLa", "types": ["movie", "series"]},
    {"id": "cinecalidadlol", "name": "CineCalidadLol", "types": ["movie", "series"]},
    {"id": "cinedeantes", "name": "CineDeAntes", "types": ["movie"]},
    {"id": "cinehdplus", "name": "CineHdPlus", "types": ["movie", "series"]},
    {"id": "cinehindi", "name": "CineHindi", "types": ["movie"]},
    {"id": "cinelibreonline", "name": "CineLibreOnline", "types": ["movie"]},
    {"id": "cinema", "name": "Cinema", "types": ["movie"]},
    {"id": "cinematteflix", "name": "CineMatteFlix", "types": ["movie"]},
    {"id": "cinemitas", "name": "CineMitas", "types": ["movie", "series"]},
    {"id": "cineplay", "name": "CinePlay", "types": ["movie", "series"]},
    {"id": "cineplus", "name": "CinePlus", "types": ["movie"]},
    {"id": "cineteca", "name": "CineTeca", "types": ["movie"]},
    {"id": "creyente", "name": "Creyente", "types": ["movie", "series"]},
    {"id": "cuevana2", "name": "Cuevana2", "types": ["movie", "series"]},
    {"id": "cuevana2esp", "name": "Cuevana2Esp", "types": ["movie", "series"]},
    {"id": "cuevana3pro", "name": "Cuevana3Pro", "types": ["movie", "series"]},
    {"id": "cuevana3re", "name": "Cuevana3Re", "types": ["movie", "series"]},
    {"id": "cuevana3run", "name": "Cuevana3Run", "types": ["movie", "series"]},
    {"id": "cumlouder", "name": "CumLouder", "types": ["movie"]},
    {"id": "daftsex", "name": "DaftSex", "types": ["movie"]},
    {"id": "detodo", "name": "DeTodo", "types": ["movie"]},
    {"id": "divxatope", "name": "DivxATope", "types": ["movie", "series"]},
    {"id": "divxtotal", "name": "DivxTotal", "types": ["movie", "series"]},
    {"id": "documentaleson", "name": "DocumentalesOn", "types": ["movie", "series"]},
    {"id": "documentalesonline", "name": "DocumentalesOnline", "types": ["movie", "series"]},
    {"id": "documentaryheaven", "name": "DocumentaryHeaven", "types": ["movie", "series"]},
    {"id": "documentarystorm", "name": "DocumentaryStorm", "types": ["movie", "series"]},
    {"id": "dontorrents", "name": "DonTorrents", "types": ["movie", "series"]},
    {"id": "dontorrentsin", "name": "DonTorrentsIn", "types": ["movie", "series"]},
    {"id": "doramaexpress", "name": "DoramaExpress", "types": ["movie", "series"]},
    {"id": "doramasflix", "name": "DoramasFlix", "types": ["movie", "series"]},
    {"id": "doramasmp4dev", "name": "DoramasMp4Dev", "types": ["series"]},
    {"id": "doramasqueenin", "name": "DoramasQueenIn", "types": ["series"]},
    {"id": "doramasyt", "name": "DoramasYt", "types": ["movie", "series"]},
    {"id": "doramedplaylat", "name": "DoramedPlayLat", "types": ["movie", "series"]},
    {"id": "dpeliculas", "name": "DPeliculas", "types": ["movie"]},
    {"id": "elifilms", "name": "EliFilms", "types": ["movie", "series"]},
    {"id": "elitedivx", "name": "EliteDivx", "types": ["movie", "series"]},
    {"id": "elitetorrent", "name": "EliteTorrent", "types": ["movie", "series"]},
    {"id": "elitetorrentnz", "name": "EliteTorrentNz", "types": ["movie", "series"]},
    {"id": "ennovelastv", "name": "EnNovelasTv", "types": ["series"]},
    {"id": "entrepeliculasyseries", "name": "EntrePeliculasySeries", "types": ["movie", "series"]},
    {"id": "eporner", "name": "EPorner", "types": ["movie"]},
    {"id": "estrenosanime", "name": "EstrenosAnime", "types": ["series"]},
    {"id": "estrenoscinesaa", "name": "EstrenosCinesaA", "types": ["movie"]},
    {"id": "estrenosdoramases", "name": "EstrenosDoramasEs", "types": ["series"]},
    {"id": "eztv", "name": "EzTv", "types": ["series"]},
    {"id": "flixcorn", "name": "FlixCorn", "types": ["series"]},
    {"id": "frozenlayer", "name": "FrozenLayer", "types": ["series"]},
    {"id": "genteclic", "name": "GenteClic", "types": ["movie"]},
    {"id": "gnula", "name": "Gnula", "types": ["movie", "series"]},
    {"id": "gnula24", "name": "Gnula24", "types": ["series"]},
    {"id": "gnula24h", "name": "Gnula24H", "types": ["series"]},
    {"id": "gnulacenter", "name": "GnulaCenter", "types": ["movie", "series"]},
    {"id": "grantorrent", "name": "GranTorrent", "types": ["movie", "series"]},
    {"id": "hacktorrent", "name": "HackTorrent", "types": ["movie", "series"]},
    {"id": "hdcinema", "name": "HdCinema", "types": ["movie", "series"]},
    {"id": "hdfull", "name": "HdFull", "types": ["movie", "series"]},
    {"id": "henaojara", "name": "HenaOjara", "types": ["series"]},
    {"id": "henaojaran", "name": "HenaOjaraN", "types": ["series"]},
    {"id": "hentaiid", "name": "HentaiId", "types": ["movie"]},
    {"id": "hentaijl", "name": "HentaiJl", "types": ["movie"]},
    {"id": "hentaila", "name": "HentaiLa", "types": ["movie"]},
    {"id": "hentaisd", "name": "HentaiSd", "types": ["movie"]},
    {"id": "homecine", "name": "HomeCine", "types": ["movie", "series"]},
    {"id": "jizzbunker", "name": "JizzBunker", "types": ["movie"]},
    {"id": "jkanime", "name": "JKAnime", "types": ["series"]},
    {"id": "joinclub", "name": "JoinClub", "types": ["movie", "series"]},
    {"id": "lacartoons", "name": "LaCartoons", "types": ["series"]},
    {"id": "lamovie", "name": "LaMovie", "types": ["movie", "series"]},
    {"id": "latanime", "name": "LatAnime", "types": ["series"]},
    {"id": "legalmentegratis", "name": "LegalmenteGratis", "types": ["movie"]},
    {"id": "lilatorrent", "name": "LilaTorrent", "types": ["movie", "series"]},
    {"id": "mangoporn", "name": "MangoPorn", "types": ["movie"]},
    {"id": "mbstelenovelas", "name": "MbsTeleNovelas", "types": ["series"]},
    {"id": "megaserie", "name": "MegaSerie", "types": ["movie", "series"]},
    {"id": "mejortorrentapp", "name": "MejorTorrentApp", "types": ["movie", "series"]},
    {"id": "mejortorrentnz", "name": "MejorTorrentNz", "types": ["movie", "series"]},
    {"id": "mitorrent", "name": "MiTorrent", "types": ["movie", "series"]},
    {"id": "monoschinos", "name": "MonosChinos", "types": ["series"]},
    {"id": "motherless", "name": "MotherLess", "types": ["movie"]},
    {"id": "moviesdvdr", "name": "MoviesDvdr", "types": ["movie"]},
    {"id": "mundodesconocido", "name": "MundoDesconocido", "types": ["movie", "series"]},
    {"id": "mundodonghua", "name": "MundoDonghua", "types": ["series"]},
    {"id": "mundodonghuaxyz", "name": "MundoDonghuaXyz", "types": ["series"]},
    {"id": "naranjatorrent", "name": "NaranjaTorrent", "types": ["movie", "series"]},
    {"id": "netnovelas", "name": "NetNovelas", "types": ["series"]},
    {"id": "novelas", "name": "Novelas", "types": ["series"]},
    {"id": "novelas360", "name": "Novelas360", "types": ["series"]},
    {"id": "nuvid", "name": "NuVid", "types": ["movie"]},
    {"id": "onlinetv", "name": "OnlineTv", "types": ["series"]},
    {"id": "osjonosu", "name": "OsjoNosu", "types": ["movie", "series"]},
    {"id": "pandamovies", "name": "PandaMovies", "types": ["movie"]},
    {"id": "pandramaio", "name": "PanDramaIo", "types": ["movie", "series"]},
    {"id": "papayaseries", "name": "PapayaSeries", "types": ["series"]},
    {"id": "paradisehill", "name": "ParadiseHill", "types": ["movie"]},
    {"id": "pasateatorrent", "name": "PasateATorrent", "types": ["movie", "series"]},
    {"id": "pediatorrent", "name": "PediaTorrent", "types": ["movie", "series"]},
    {"id": "peliculasflix", "name": "PeliculasFlix", "types": ["movie"]},
    {"id": "peliculaspro", "name": "PeliculasPro", "types": ["movie", "series"]},
    {"id": "pelis182", "name": "Pelis182", "types": ["movie"]},
    {"id": "pelis28re", "name": "Pelis28Re", "types": ["movie", "series"]},
    {"id": "pelisforte", "name": "PelisForte", "types": ["movie"]},
    {"id": "pelisgratishd", "name": "PelisGratisHd", "types": ["movie", "series"]},
    {"id": "pelismart", "name": "PelisMart", "types": ["movie", "series"]},
    {"id": "pelispanda", "name": "PelisPanda", "types": ["movie", "series"]},
    {"id": "pelispediais", "name": "PelisPediaIs", "types": ["movie", "series"]},
    {"id": "pelispediaws", "name": "PelisPediaWs", "types": ["movie"]},
    {"id": "pelisplayhd", "name": "PelisPlayHd", "types": ["movie", "series"]},
    {"id": "pelisplushd", "name": "PelisPlusHd", "types": ["movie", "series"]},
    {"id": "pelisplushdlat", "name": "PelisPlusHdLat", "types": ["movie", "series"]},
    {"id": "pelisplushdnz", "name": "PelisPlusHdNz", "types": ["movie", "series"]},
    {"id": "pelisyseries", "name": "PelisySeries", "types": ["movie", "series"]},
    {"id": "pgratishd", "name": "PGratisHd", "types": ["movie", "series"]},
    {"id": "playplus", "name": "PlayPlus", "types": ["movie", "series"]},
    {"id": "plushd", "name": "PlusHd", "types": ["movie", "series"]},
    {"id": "pornburst", "name": "PornBurst", "types": ["movie"]},
    {"id": "porndoe", "name": "PornDoe", "types": ["movie"]},
    {"id": "porndude", "name": "PornDude", "types": ["movie"]},
    {"id": "pornhub", "name": "PornHub", "types": ["movie"]},
    {"id": "pornxbit", "name": "PornXbit", "types": ["movie"]},
    {"id": "poseidonhd2", "name": "PoseidonHd2", "types": ["movie", "series"]},
    {"id": "rarbg", "name": "RarBg", "types": ["movie", "series"]},
    {"id": "redtube", "name": "RedTube", "types": ["movie"]},
    {"id": "reinventorrent", "name": "ReinvenTorrent", "types": ["movie", "series"]},
    {"id": "repelishd", "name": "RePelisHd", "types": ["movie", "series"]},
    {"id": "retrotv", "name": "RetroTv", "types": ["movie", "series"]},
    {"id": "rojotorrent", "name": "RojoTorrent", "types": ["movie", "series"]},
    {"id": "series24", "name": "Series24", "types": ["series"]},
    {"id": "seriesbiblicas", "name": "SeriesBiblicas", "types": ["movie", "series"]},
    {"id": "seriesgod", "name": "SeriesGod", "types": ["series"]},
    {"id": "serieskao", "name": "SeriesKao", "types": ["movie", "series"]},
    {"id": "seriesmetron", "name": "SeriesMetroN", "types": ["movie", "series"]},
    {"id": "seriesonline", "name": "SeriesOnline", "types": ["series"]},
    {"id": "seriespapayato", "name": "SeriesPapayaTo", "types": ["movie", "series"]},
    {"id": "seriesplus", "name": "SeriesPlus", "types": ["series"]},
    {"id": "seriesretro", "name": "SeriesRetro", "types": ["movie", "series"]},
    {"id": "seriesturcas", "name": "SeriesTurcas", "types": ["series"]},
    {"id": "serviporno", "name": "ServiPorno", "types": ["movie"]},
    {"id": "sigloxx", "name": "SigloXX", "types": ["movie"]},
    {"id": "sololatino", "name": "SoloLatino", "types": ["movie", "series"]},
    {"id": "srnovelas", "name": "SrNovelas", "types": ["series"]},
    {"id": "star", "name": "Star", "types": ["series"]},
    {"id": "subtorrents", "name": "SubTorrents", "types": ["movie", "series"]},
    {"id": "t1337x", "name": "T1337X", "types": ["movie", "series"]},
    {"id": "tioanime", "name": "TioAnime", "types": ["series"]},
    {"id": "tiodonghua", "name": "TioDonghua", "types": ["series"]},
    {"id": "todotorrents", "name": "TodoTorrents", "types": ["movie", "series"]},
    {"id": "tomadivx", "name": "TomaDivx", "types": ["movie", "series"]},
    {"id": "topdocumentaryfilms", "name": "TopDocumentaryFilms", "types": ["movie", "series"]},
    {"id": "torrentgalaxy", "name": "TorrentGalaxy", "types": ["movie", "series"]},
    {"id": "trailers", "name": "Trailers", "types": ["movie"]},
    {"id": "tubehentai", "name": "TubeHentai", "types": ["movie"]},
    {"id": "tubeonline", "name": "TubeOnline", "types": ["movie"]},
    {"id": "tubepelis", "name": "TubePelis", "types": ["movie"]},
    {"id": "tucineclasico", "name": "TuCineClasico", "types": ["movie"]},
    {"id": "tvseries", "name": "TvSeries", "types": ["series"]},
    {"id": "ultrapelis", "name": "UltraPelis", "types": ["movie"]},
    {"id": "veranime", "name": "VerAnime", "types": ["series"]},
    {"id": "verdetorrent", "name": "VerdeTorrent", "types": ["movie", "series"]},
    {"id": "verdocumentalesonline", "name": "VerDocumentalesOnline", "types": ["movie", "series"]},
    {"id": "verflix", "name": "VerFlix", "types": ["series"]},
    {"id": "vernovelas", "name": "VerNovelas", "types": ["series"]},
    {"id": "veronline", "name": "VerOnline", "types": ["series"]},
    {"id": "verpelis", "name": "VerPelis", "types": ["movie", "series"]},
    {"id": "verseries", "name": "VerSeries", "types": ["movie", "series"]},
    {"id": "villaanimex", "name": "VillaAnimex", "types": ["series"]},
    {"id": "vivatorrents", "name": "VivaTorrents", "types": ["movie"]},
    {"id": "watchpornfree", "name": "WatchPornFree", "types": ["movie"]},
    {"id": "xmfy", "name": "XmFy", "types": ["movie"]},
    {"id": "xmoviesforyou", "name": "XMoviesForYou", "types": ["movie"]},
    {"id": "xvideos", "name": "XVideos", "types": ["movie"]},
    {"id": "xxxdan", "name": "XxxDan", "types": ["movie"]},
    {"id": "yandispoiler", "name": "YandiSpoiler", "types": ["movie", "series"]},
    {"id": "yespornplease", "name": "YesPornPlease", "types": ["movie"]},
    {"id": "yohentai", "name": "YoHentai", "types": ["movie"]},
    {"id": "youjizz", "name": "YouJizz", "types": ["movie"]},
    {"id": "youtubedocs", "name": "YouTubeDocs", "types": ["movie", "series"]},
    {"id": "yts", "name": "Yts", "types": ["movie"]},
    {"id": "ytsmx", "name": "YtsMx", "types": ["movie"]},
    {"id": "zbporn", "name": "ZbPorn", "types": ["movie"]},
    {"id": "zerowpanime", "name": "ZeroWpAnime", "types": ["series"]},
    {"id": "zonaleros", "name": "ZonaLeros", "types": ["movie", "series"]},
    {"id": "zonapelis", "name": "ZonaPelis", "types": ["movie", "series"]},
    {"id": "zoowomaniacos", "name": "ZoowoManiacos", "types": ["movie"]},
]
